name: "CloudThread Tag Assistant check"
description: "Checks if Terraform modules have default tag present in AWS provider configuration"
inputs:
  terraform-path:
    description: "Terraform configuration path"
    required: false
    default: '.'
  cloudthread-token:
    description: "The token to authenticate with CloudThread API endpoint"
    required: true
  catalog-key:
    description: >
      Catalog key that determies the teg set to be assigned by default to all the resources created by
      Terraform configuration in this repository
    required: true
  tag-assistant-version:
    default: 2.2.1
    description: "Version to run"
  api-root:
    description: CloudThread API URL
    required: false
    default: "https://api.cloudthread.io/"
  region:
    description: Preferred AWS region (only us-west-2 is supported currently)
    required: false
    default: "us-west-2"
runs:
  using: "composite"
  steps:
    - name: Get AWS credentials
      id: get-ct-aws-creds
      uses: cloudthread/ecr-login-action@v1
      with:
        cloudthread-token: ${{ inputs.cloudthread-token }}
        api-root: ${{ inputs.api-root }}
        region: ${{ inputs.region }}
    - name: Run TA docker image
      uses: addnab/docker-run-action@v3
      with:
          username: ${{ steps.get-ct-aws-creds.outputs.username }}
          password: ${{ steps.get-ct-aws-creds.outputs.token }}
          registry: ${{ steps.get-ct-aws-creds.outputs.registry }}
          image: ${{ steps.get-ct-aws-creds.outputs.registry }}/tag-assistant:${{ inputs.tag-assistant-version }}
          options: -v ${{ github.workspace }}:/opt/repo
          run: |
              ./opt/ta/cloudthread-assistant --base-branch=${{ github.head_ref }} /opt/repo/${{ inputs.terraform-path }} --ghtoken=${{ github.token }} --repo=${{ github.repository }} --token=${{ inputs.cloudthread-token }} --key=${{ inputs.catalog-key }} --api-root=${{ inputs.api-root }}
